package model;
// Generated Jul 23, 2020 4:37:34 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Inbox generated by hbm2java
 */
@Entity
@Table(name="inbox"
    ,catalog="bahaushi_projectdb"
)
public class Inbox  implements java.io.Serializable {


     private Integer id;
     private Person person;
     private Integer personid;
     private String roomid;
     private Integer inbox;

    public Inbox() {
    }

    public Inbox(Person person, Integer personid, String roomid, Integer inbox) {
       this.person = person;
       this.personid = personid;
       this.roomid = roomid;
       this.inbox = inbox;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="messagefrom")
    public Person getPerson() {
        return this.person;
    }
    
    public void setPerson(Person person) {
        this.person = person;
    }

    
    @Column(name="personid")
    public Integer getPersonid() {
        return this.personid;
    }
    
    public void setPersonid(Integer personid) {
        this.personid = personid;
    }

    
    @Column(name="roomid", length=20)
    public String getRoomid() {
        return this.roomid;
    }
    
    public void setRoomid(String roomid) {
        this.roomid = roomid;
    }

    
    @Column(name="inbox")
    public Integer getInbox() {
        return this.inbox;
    }
    
    public void setInbox(Integer inbox) {
        this.inbox = inbox;
    }




}
