package model;
// Generated Jul 23, 2020 4:37:34 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Inbox generated by hbm2java
 */
@Entity
@Table(name = "mail",
        catalog = "bahaushi_projectdb"
)
public class Mail implements java.io.Serializable {

    private Integer id;
    private Person person;
    private String mail;
    private Date sendtime;
    private Integer inbox;

    public Mail() {
    }

    public Mail(Person person, String mail, Date sendtime, Integer inbox) {
        this.person = person;
        this.mail = mail;
        this.sendtime = sendtime;
        this.inbox = inbox;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "messagefrom")
    public Person getPerson() {
        return this.person;
    }

    public void setPerson(Person person) {
        this.person = person;
    }

    @Column(name = "inbox")
    public Integer getInbox() {
        return this.inbox;
    }

    public void setInbox(Integer inbox) {
        this.inbox = inbox;
    }

    @Column(name = "mail")
    public String getMail() {
        return mail;
    }

    public void setMail(String mail) {
        this.mail = mail;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "sendtime", length = 10)
    public Date getSendtime() {
        return sendtime;
    }

    public void setSendtime(Date sendtime) {
        this.sendtime = sendtime;
    }

}
