package model;
// Generated Jul 21, 2020 4:40:33 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Message generated by hbm2java
 */
@Entity
@Table(name="message"
    ,catalog="bahaushi_projectdb"
)
public class Message  implements java.io.Serializable {


     private Integer id;
     private String roomid;
     private Integer messagefrom;
     private Integer messageto;
     private String content;
     private Date sendtime;

    public Message() {
    }

    public Message(String roomid, Integer messagefrom, Integer messageto, String content, Date sendtime) {
       this.roomid = roomid;
       this.messagefrom = messagefrom;
       this.messageto = messageto;
       this.content = content;
       this.sendtime = sendtime;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="roomid", length=20)
    public String getRoomid() {
        return this.roomid;
    }
    
    public void setRoomid(String roomid) {
        this.roomid = roomid;
    }

    
    @Column(name="messagefrom")
    public Integer getMessagefrom() {
        return this.messagefrom;
    }
    
    public void setMessagefrom(Integer messagefrom) {
        this.messagefrom = messagefrom;
    }

    
    @Column(name="messageto")
    public Integer getMessageto() {
        return this.messageto;
    }
    
    public void setMessageto(Integer messageto) {
        this.messageto = messageto;
    }

    
    @Column(name="content")
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }

   @Temporal(TemporalType.DATE)
    @Column(name = "sendtime", length = 10)
    public Date getSendtime() {
        return sendtime;
    }

    public void setSendtime(Date sendtime) {
        this.sendtime = sendtime;
    }

}


