package model;
// Generated Jul 21, 2020 4:40:33 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Message generated by hbm2java
 */
@Entity
@Table(name="notification"
    ,catalog="bahaushi_projectdb"
)
public class Notification  implements java.io.Serializable {


     private Integer id;
     private Integer messageto;
     private String content;
     private Date sendtime;
     private Integer status;

    public Notification() {
    }

    public Notification(Integer messageto, String content, Date sendtime,Integer status) {
       this.messageto = messageto;
       this.content = content;
       this.sendtime = sendtime;
       this.status=status;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="messageto")
    public Integer getMessageto() {
        return this.messageto;
    }
    
    public void setMessageto(Integer messageto) {
        this.messageto = messageto;
    }

    
    @Column(name="content")
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "sendtime", length = 10)
    public Date getSendtime() {
        return sendtime;
    }

    public void setSendtime(Date sendtime) {
        this.sendtime = sendtime;
    }
    @Column(name="status")
    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }
    
    

}


