package model;
// Generated Jul 16, 2020 2:10:18 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Person generated by hbm2java
 */
@Entity
@Table(name = "person",
        catalog = "bahaushi_projectdb"
)
public class Person implements java.io.Serializable {

    private Integer id;
    private User user;
    private String firstname;
    private String lastname;
    private String sex;
    private String religion;
    private String image;
    private String bio;
    private String profession;
    private String height;
    private String hair;
    private Integer education;
    private String lookingfor;
    private String kids;
    private String race;
    private String nationality;
    private String language;
    private String physique;
    private String maritalstatus;
    private String dob;
    private String favfood;
    private String favcolor;
    private String country;
    private String city;
    private Integer age;
    private String imageapproval;
    private String bioapproval;
    private String reviewed;

    public Person() {
    }

    public Person(User user, String firstname, String lastname, String sex,
            String religion, String image, String bio, String profession,
            String height, String hair, Integer education, String lookingfor,
            String kids, String race, String nationality, String language,
            String physique, String maritalstatus, String dob, String favfood,
            String favcolor, String country, String city, Integer age, String imageapproval,
            String bioapproval, String reviewed) {
        this.user = user;
        this.firstname = firstname;
        this.lastname = lastname;
        this.sex = sex;
        this.religion = religion;
        this.image = image;
        this.bio = bio;
        this.profession = profession;
        this.height = height;
        this.hair = hair;
        this.education = education;
        this.lookingfor = lookingfor;
        this.kids = kids;
        this.race = race;
        this.nationality = nationality;
        this.language = language;
        this.physique = physique;
        this.maritalstatus = maritalstatus;
        this.dob = dob;
        this.favfood = favfood;
        this.favcolor = favcolor;
        this.country = country;
        this.city = city;
        this.age = age;
        this.bioapproval = bioapproval;
        this.imageapproval = imageapproval;
        this.reviewed = reviewed;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "UserID")
    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    @Column(name = "firstname", length = 100)
    public String getFirstname() {
        return this.firstname;
    }

    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    @Column(name = "lastname", length = 100)
    public String getLastname() {
        return this.lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    @Column(name = "sex", length = 10)
    public String getSex() {
        return this.sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }

    @Column(name = "religion", length = 20)
    public String getReligion() {
        return this.religion;
    }

    public void setReligion(String religion) {
        this.religion = religion;
    }

    @Column(name = "image", length = 100)
    public String getImage() {
        return this.image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    @Column(name = "bio")
    public String getBio() {
        return this.bio;
    }

    public void setBio(String bio) {
        this.bio = bio;
    }

    @Column(name = "profession")
    public String getProfession() {
        return this.profession;
    }

    public void setProfession(String profession) {
        this.profession = profession;
    }

    @Column(name = "height", length = 10)
    public String getHeight() {
        return this.height;
    }

    public void setHeight(String height) {
        this.height = height;
    }

    @Column(name = "hair", length = 10)
    public String getHair() {
        return this.hair;
    }

    public void setHair(String hair) {
        this.hair = hair;
    }

    @Column(name = "education")
    public Integer getEducation() {
        return this.education;
    }

    public void setEducation(Integer education) {
        this.education = education;
    }

    @Column(name = "lookingfor")
    public String getLookingfor() {
        return this.lookingfor;
    }

    public void setLookingfor(String lookingfor) {
        this.lookingfor = lookingfor;
    }

    @Column(name = "kids", length = 20)
    public String getKids() {
        return this.kids;
    }

    public void setKids(String kids) {
        this.kids = kids;
    }

    @Column(name = "race", length = 20)
    public String getRace() {
        return this.race;
    }

    public void setRace(String race) {
        this.race = race;
    }

    @Column(name = "nationality", length = 100)
    public String getNationality() {
        return this.nationality;
    }

    public void setNationality(String nationality) {
        this.nationality = nationality;
    }

    @Column(name = "language", length = 100)
    public String getLanguage() {
        return this.language;
    }

    public void setLanguage(String language) {
        this.language = language;
    }

    @Column(name = "physique", length = 100)
    public String getPhysique() {
        return this.physique;
    }

    public void setPhysique(String physique) {
        this.physique = physique;
    }

    @Column(name = "maritalstatus", length = 100)
    public String getMaritalstatus() {
        return this.maritalstatus;
    }

    public void setMaritalstatus(String maritalstatus) {
        this.maritalstatus = maritalstatus;
    }

    @Column(name = "dob")
    public String getDob() {
        return this.dob;
    }

    public void setDob(String dob) {
        this.dob = dob;
    }

    @Column(name = "favfood", length = 100)
    public String getFavfood() {
        return this.favfood;
    }

    public void setFavfood(String favfood) {
        this.favfood = favfood;
    }

    @Column(name = "favcolor", length = 100)
    public String getFavcolor() {
        return this.favcolor;
    }

    public void setFavcolor(String favcolor) {
        this.favcolor = favcolor;
    }

    @Column(name = "country", length = 100)
    public String getCountry() {
        return this.country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    @Column(name = "city", length = 100)
    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    @Column(name = "age")
    public Integer getAge() {
        return age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

    @Column(name = "imageapproval")
    public String getImageapproval() {
        return imageapproval;
    }

    public void setImageapproval(String imageapproval) {
        this.imageapproval = imageapproval;
    }

    @Column(name = "bioapproval")
    public String getBioapproval() {
        return bioapproval;
    }

    public void setBioapproval(String bioapproval) {
        this.bioapproval = bioapproval;
    }

    @Column(name = "reviewed")
    public String getReviewed() {
        return reviewed;
    }

    public void setReviewed(String reviewed) {
        this.reviewed = reviewed;
    }

}
