package model;
// Generated Aug 3, 2020 1:06:45 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Stories generated by hbm2java
 */
@Entity
@Table(name="stories"
    ,catalog="bahaushi_projectdb"
)
public class Stories  implements java.io.Serializable {


     private Integer id;
     private Person personByPerson1;
     private Person personByPerson2;
     private String storyhead;
     private String story;
     private String image;

    public Stories() {
    }

    public Stories(Person personByPerson1, Person personByPerson2, String storyhead, String story, String image) {
       this.personByPerson1 = personByPerson1;
       this.personByPerson2 = personByPerson2;
       this.storyhead = storyhead;
       this.story = story;
       this.image = image;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="PERSON1")
    public Person getPersonByPerson1() {
        return this.personByPerson1;
    }
    
    public void setPersonByPerson1(Person personByPerson1) {
        this.personByPerson1 = personByPerson1;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="PERSON2")
    public Person getPersonByPerson2() {
        return this.personByPerson2;
    }
    
    public void setPersonByPerson2(Person personByPerson2) {
        this.personByPerson2 = personByPerson2;
    }

    
    @Column(name="STORYHEAD")
    public String getStoryhead() {
        return this.storyhead;
    }
    
    public void setStoryhead(String storyhead) {
        this.storyhead = storyhead;
    }

    
    @Column(name="STORY")
    public String getStory() {
        return this.story;
    }
    
    public void setStory(String story) {
        this.story = story;
    }

    
    @Column(name="IMAGE", length=100)
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }




}


