package model;
// Generated Jul 30, 2020 8:11:31 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Transactionlog generated by hbm2java
 */
@Entity
@Table(name = "transactionlog",
        catalog = "bahaushi_projectdb"
)
public class Transactionlog implements java.io.Serializable {

    private Integer id;
    private User user;
    private String referenceno;
    private String subtype;
    private Date datelog;

    public Transactionlog() {
    }

    public Transactionlog(User user, String referenceno, String subtype, Date datelog) {
        this.user = user;
        this.referenceno = referenceno;
        this.subtype = subtype;
        this.datelog = datelog;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "userid")
    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    @Column(name = "REFERENCENO", length = 100)
    public String getReferenceno() {
        return this.referenceno;
    }

    public void setReferenceno(String referenceno) {
        this.referenceno = referenceno;
    }

    @Column(name = "subtype", length = 100)
    public String getSubtype() {
        return subtype;
    }

    public void setSubtype(String subtype) {
        this.subtype = subtype;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "datelog", length = 10)
    public Date getDatelog() {
        return this.datelog;
    }

    public void setDatelog(Date datelog) {
        this.datelog = datelog;
    }

}
